[package]
name = "bedrock_asset"
version = "1.0.0"
authors = []

[dependencies]
AptosFramework = { git = "https://github.com/movementlabsxyz/aptos-core", rev = "movement", subdir = "aptos-move/framework/aptos-framework" }

[addresses]
std = "0x1"
admin = "_"
bedrock_asset = "_"
