[package]
name = "free_tunnel_rooch"
version = "1.0.0"
authors = []

[addresses]
std = "0x1"
free_tunnel_rooch = "0xa057ec0bff69d3e9a761337f8d6d9a742e93be316ba3062747af2734c96f2c15"

[dev-addresses]

[dependencies]
MoveStdlib = { git = "https://github.com/rooch-network/rooch.git", subdir = "frameworks/move-stdlib", rev = "main" }
MoveosStdlib = { git = "https://github.com/rooch-network/rooch.git", subdir = "frameworks/moveos-stdlib", rev = "main" }
RoochFramework = { git = "https://github.com/rooch-network/rooch.git", subdir = "frameworks/rooch-framework", rev = "main" }

[dev-dependencies]
