name: Move CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    
  aptos-build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Aptos CLI
        run: |
          if command -v curl > /dev/null; then
            curl -fsSL "https://aptos.dev/scripts/install_cli.py" | python3
          else
            wget -qO- "https://aptos.dev/scripts/install_cli.py" | python3
          fi
      
      - name: Build Aptos modules
        run: aptos move build
      
      - name: Run Aptos tests
        run: aptos move test
